const API_URL='https://script.google.com/macros/s/YOUR_DEPLOYMENT_ID/exec';
const $=id=>document.getElementById(id);
const state={customer:null};
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
async function api(payload){if(API_URL.includes('PASTE_'))throw Error('Please connect your Apps Script Web App URL in app.js.');const r=await fetch(API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(payload)});const j=await r.json();if(!j.ok)throw Error(j.error||'Request failed');return j}
function render(c){state.customer=c;$('available').textContent=c.available||0;$('earned').textContent=c.earned||0;$('redeemed').textContent=c.redeemed||0;$('pending').textContent=c.pending||0;$('dashboard').classList.remove('hidden');$('ledger').innerHTML=(c.bills||[]).map(x=>`<tr><td>${esc(x.date)}</td><td>${esc(x.bill)}</td><td>₹${Number(x.amount||0).toLocaleString('en-IN')}</td><td>${esc(x.points||0)}</td><td>${esc(x.status)}</td><td>${esc(x.reason||'-')}</td></tr>`).join('')||'<tr><td colspan="6">No bills submitted yet.</td></tr>'}
if($('customerForm')){
  $('theme').onclick=()=>{const d=document.documentElement.getAttribute('data-theme')==='dark';document.documentElement.setAttribute('data-theme',d?'light':'dark');$('theme').textContent=d?'☾':'☀'};
  $('customerForm').onsubmit=async e=>{e.preventDefault();$('customerMsg').textContent='Loading...';try{const r=await api({action:'customerGet',name:$('name').value.trim(),phone:$('phone').value.replace(/\D/g,'')});render(r.customer);$('customerMsg').textContent=''}catch(x){$('customerMsg').textContent=x.message}};
  $('billForm').onsubmit=async e=>{e.preventDefault();if(!state.customer)return;$('billMsg').textContent='Submitting...';const f=$('photo').files[0];if(!f)return $('billMsg').textContent='Please select the bill photo.';try{if(Number($('amount').value)<999)throw Error('Minimum qualifying bill is ₹999.');const reader=new FileReader();const data=await new Promise((res,rej)=>{reader.onload=()=>res(reader.result);reader.onerror=rej;reader.readAsDataURL(f)});await api({action:'submitBill',customerId:state.customer.id,name:state.customer.name,phone:state.customer.phone,billNumber:$('bill').value.trim(),billAmount:Number($('amount').value),purchaseDate:$('date').value,billPhoto:data});$('billMsg').textContent='Bill submitted successfully. Waiting for owner approval.';e.target.reset();$('date').value=new Date().toISOString().slice(0,10);render((await api({action:'customerGet',phone:state.customer.phone})).customer)}catch(x){$('billMsg').textContent=x.message}};
  $('redeem').onclick=async()=>{if(!state.customer)return;$('redeemMsg').textContent='Submitting...';try{const r=await api({action:'redeem',customerId:state.customer.id,phone:state.customer.phone});$('redeemMsg').textContent=r.message;render((await api({action:'customerGet',phone:state.customer.phone})).customer)}catch(x){$('redeemMsg').textContent=x.message}};
  $('date').value=new Date().toISOString().slice(0,10);
}
window.PRAKSH_API_URL=API_URL;
