const OWNER_API_URL=window.PRAKSH_API_URL;
const $o=id=>document.getElementById(id);
const token=sessionStorage.getItem('ownerToken');
if(!token) location.href='owner-login.html';
function escO(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
async function ownerApi(p){if(OWNER_API_URL.includes('PASTE_'))throw Error('Please connect your Apps Script Web App URL in app.js.');const r=await fetch(OWNER_API_URL,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({...p,token})});const j=await r.json();return j}
async function loadOwner(){try{const r=await ownerApi({action:'ownerData'});if(!r.ok)throw Error(r.error||'Unable to load owner dashboard.');$o('customers').textContent=r.stats.customers;$o('pendingBillsCount').textContent=r.stats.pendingBills;$o('issued').textContent=r.stats.issued;$o('ownerRedeemed').textContent=r.stats.redeemed;$o('pending').innerHTML=r.pending.map(x=>`<tr><td>${escO(x.name)}</td><td>${escO(x.phone)}</td><td>${escO(x.bill)}</td><td>₹${Number(x.amount||0).toLocaleString('en-IN')}</td><td>${escO(x.date)}</td><td>${x.photo?`<a href="${escO(x.photo)}" target="_blank" rel="noopener">View Bill</a>`:'-'}</td><td><button onclick="approveBill('${escO(x.id)}')">Approve</button> <button onclick="rejectBill('${escO(x.id)}')">Reject</button></td></tr>`).join('')||'<tr><td colspan="7">No pending bills.</td></tr>';renderCustomers(r.customers)}catch(e){alert(e.message);if(/session|login/i.test(e.message)){sessionStorage.removeItem('ownerToken');location.href='owner-login.html'}}}
function renderCustomers(cs){const q=$o('search').value.toLowerCase();$o('customersTable').innerHTML=cs.filter(c=>(c.name+' '+c.phone).toLowerCase().includes(q)).map(c=>`<tr><td>${escO(c.name)}</td><td>${escO(c.phone)}</td><td>${c.bills}</td><td>${c.earned}</td><td>${c.redeemed}</td><td>${c.available}</td></tr>`).join('')||'<tr><td colspan="6">No customers found.</td></tr>'}
async function approveBill(id){if(!confirm('Approve this bill and issue points?'))return;const r=await ownerApi({action:'approveBill',billId:id});if(!r.ok)return alert(r.error||'Approval failed.');await loadOwner()}
async function rejectBill(id){const reason=prompt('Reason for rejection:','Bill could not be verified');if(reason===null)return;const r=await ownerApi({action:'rejectBill',billId:id,reason});if(!r.ok)return alert(r.error||'Rejection failed.');await loadOwner()}
$o('refresh').onclick=loadOwner;$o('search').oninput=loadOwner;$o('logout').onclick=()=>{sessionStorage.removeItem('ownerToken');location.href='owner-login.html'};$o('theme').onclick=()=>{const d=document.documentElement.getAttribute('data-theme')==='dark';document.documentElement.setAttribute('data-theme',d?'light':'dark');$o('theme').textContent=d?'☾':'☀'};loadOwner();
